const books = [
  {
    id: 1,
    title: "Electronics",
    author: "Prof. Inasu A",
    publishedDate: "29-08-2021",
    semester: 5,
    subject: "Electronics",
    path: "assets/pdf/electronics.pdf",
    cover: "assets/img/electronics.jpg",
    isReference: false,
    category: [""],
    pages: 195,
  },
  {
    id: 2,
    title: "Quantum Mechanics",
    author: "Prof. Lenard A",
    publishedDate: "29-08-2021",
    semester: 5,
    subject: "Quantum mechanics",
    path: "assets/pdf/quantum.pdf",
    cover: "assets/img/quantum.jpg",
    isReference: false,
    category: [""],
    pages: 155,
  },
  {
    id: 3,
    title: "Optics",
    author: "Prof. Daniel Devasia",
    publishedDate: "29-08-2021",
    semester: 5,
    subject: "Optics",
    path: "assets/pdf/optics.pdf",
    cover: "assets/img/optics.jpg",
    isReference: false,
    category: [""],
    pages: 169,
  },
];
