const textbooks = [
  {
    id: 1,
    title: "thermodynamics",
    author: "dr. p. sethumadhavan",
    publishedDate: "29-08-2021",
    semester: 6,
    subject: ["thermodynamics"], // can have more than one value for reference books
    filepath: "/textbooks/semester-6/thermodynamics/thermodynamics.pdf",
    image: {
      url: "/textbooks/semester-6/thermodynamics/cover/thermodynamics.jpg",
      width: 126,
      height: 165,
    },
    isReference: false,
    category: [""],
    pages: 255,
  },
  {
    id: 2,
    title: "material science",
    author: "dr. p. sethumadhavan",
    publishedDate: "September 2, 2022",
    semester: 6,
    subject: ["material science"],
    filepath: "/textbooks/semester-6/material-science/material-science.pdf",
    image: {
      url: "/textbooks/semester-6/material-science/cover/material-science.jpg",
      width: 126,
      height: 165,
    },
    isReference: false,
    category: [""],
    pages: 195,
  },
  {
    id: 3,
    title: "relativistic mechanics and astrophysics",
    author: "dr. p. sethumadhavan",
    publishedDate: "August 29, 2021",
    semester: 6,
    subject: ["relativistic mechanics and astrophysics"],
    filepath: "/textbooks/semester-6/relativity/relativity.pdf",
    image: {
      url: "/textbooks/semester-6/relativity/cover/relativity.jpg",
      width: 126,
      height: 165,
    },
    isReference: false,
    category: [""],
    pages: 263,
  },
  {
    id: 4,
    title: "nuclear physics and particle physics",
    author: "dr. p. sethumadhavan",
    publishedDate: "August 29, 2021",
    semester: 6,
    subject: ["nuclear physics and particle physics"],
    filepath: "/textbooks/semester-6/nuclear-physics/nuclear-physics.pdf",
    image: {
      url: "/textbooks/semester-6/nuclear-physics/cover/nuclear-physics.jpg",
      width: 126,
      height: 165,
    },
    isReference: false,
    category: [""],
    pages: 232,
  },
  {
    id: 5,
    title: "statistical physics solid state physics and photonics",
    author: "dr. p. sethumadhavan",
    publishedDate: "August 29, 2021",
    semester: 6,
    subject: ["statistical physics solid state physics and photonics"],
    filepath:
      "/textbooks/semester-6/statistical-physics/statistical-physics.pdf",
    image: {
      url: "/textbooks/semester-6/statistical-physics/cover/statistical-physics.jpg",
      width: 126,
      height: 165,
    },
    isReference: false,
    category: [""],
    pages: 231,
  },
  // {
  //   id: 5,
  //   title: "experimental physics",
  //   author: "dr. p. sethumadhavan, prof. k.c abraham, prof. sunil john",
  //   publishedDate: "August 29, 2021",
  //   semester: 6,
  //   subject: ["experimental physics"],
  //   filepath:
  //     "/textbooks/semester-6/experimental-physics/experimental-physics.pdf",
  //   image: {
  //     url: "/textbooks/semester-6/experimental-physics/cover/experimental-physics.jpg",
  //     width: 126,
  //     height: 165,
  //   },
  //   isReference: false,
  //   category: [""],
  //   pages: 195,
  // },
  {
    id: 6,
    title: "modern physics",
    author: "Kenneth Krane",
    publishedDate: "August 29, 2021",
    semester: 6,
    subject: ["modern physics"],
    filepath: "/textbooks/semester-6/reference-books/modern-physics.pdf",
    image: {
      url: "/textbooks/semester-6/reference-books/covers/modern-physics.png",
      width: 126,
      height: 157,
    },
    isReference: true,
    category: [""],
    pages: 566,
  },
];

export { textbooks };
